# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true # we use gulp + BrowserSync for livereload
    datasource:
        url: "jdbc:mysql://127.0.0.1:3306/bluemine_1.0.0?useUnicode=true&characterEncoding=UTF-8"
        username: root
        password: 111111
bluemine:
    token: 49252889384718336
    version: 1.0.0
    tag-cache:
        expire: 1800
    scheduler:
        threadNamePrefix: task-scheduler-
        poolSize: 20
        awaitTerminationSeconds: 60
        waitForTasksToCompleteOnShutdown: true
        removeOnCancelPolicy: true
    call-sync:
        cron: 10 * * * * ?
#        cron: 1 0/1 * * * ?
        host: 127.0.0.1
        port: 21
        username: bluemine-batch
        password: 123456
        local-path: E:\workspace\bluemine\1.0.0\bluemine-batch\sync
    call-batch:
        corePoolSize: 5
        maxPoolSize: 20
        queueCapacity: 5
        keepAliveSeconds: 300
    solr:
        requestRetry: 3
        connectionMaxTotal: 200
        connectTimeout: 5000
        readTimeout: 5000
        connectionRequestTimeout: 200