# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ==================================================================
spring:
    application:
        name: ${name}
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: ${spring.profiles.active}

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        hikari:
            minimumIdle: 5
            maximumPoolSize: 30
            poolName: bluemine-datapool
            autoCommit: false
            dataSourceProperties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    batch:
        job:
          enabled: false
        initializer:
          enabled: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
            hibernate.javax.cache.uri: ${spring.cache.jcache.config}
    jackson:
        serialization.write_dates_as_timestamps: false
        serialization.indent_output: true

    messages:
        basename: i18n/messages

#    resources:
#        add-mappings: true
#        static-locations: classpath:/webapp/WEB-INF/resources

#    mvc:
#        throw-exception-if-no-handler-found: true
#        favicon:
#            enabled: false
#        view:
#            prefix: classpath:/view/
#            suffix: .jsp
#        static-path-pattern: /**

    thymeleaf:
        cache: false
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        content-type: text/html

security:
    basic:
        enabled: false

server:
    session:
        cookie:
            http-only: true
    tomcat:
        max-http-header-size: 3145728